### ISSUE TITLE
my C++ implementation gives wrong result

### ISSUE THREAD

**Issue by stla** [fremling/jacobi-theta-function-fortran#1]
Hello,

Thank you for this repo. I tried to translate your Fortran code to C++ and I don't get the correct result. I'm a bit puzzled by these two lines:

```f90
!!Reduce  -0.5 < Re(z) < 0.5
zuse = mod(real(z),1.d0) + iunit*aimag(z)
```

The modulo 1 operation gives `-1 < Re(z) < 1`, no?

I tried with `z=1+i` and `tau=0.5i`. The correct result is `0.28269-1.293911i` and this is really not what I get.

**Comment by fremling** [comment]
Hi. Just to make sure, do you think the error is in the C++ or in the Fortran code?
I agree that there probably is a typo in the comments. Indeed the `mod(x,1)` is defined to give `-1 < mod(x,1) < 1`.

The reason for this line is simply to keep the real part of the argument in a narrow range.

**Comment by fremling** [comment]
Thanks @stla for bringing this repository back into my conciseness. Looking at it i realized that I had left it in a terribly bad state. Now, however there is an extended readme page and a testsuite that one can run.

**Comment by stla** [comment]
Hello,

I think there are some errors in the Fortran code. I managed to get correct results after some modifications, but my implementation does not work for all cases.

For example I think this line is not correct:

`zmin = zuse-tau`

I replaced it with `zmin = zuse-z`.

**Comment by fremling** [comment]
I did some checking with Matematica, and now i now the root of the problem.
The code implements 

$$\theta_3(z,\tau) = \sum_{n=-\infty}^{\infty} e^{\imath \pi \tau n^2} e^{\imath 2 \pi n z}$$

which differ by a factor of $\pi$ compared no [NIST](https://dlmf.nist.gov/20) (and Mathematica)

This means that here 
$\theta_3(z+1,\tau) = \theta_3(z,\tau)$
wheas NIST has
$\theta_3(z+\pi,\tau) = \theta_3(z,\tau).$

Thus for $z=1+\imath$
 and $\tau = \imath/2$ the result should be `760.128`.

This has now been clarified in the readme.

**Comment by stla** [comment]
Ok, nice. Thanks. I will try.

First time I see some MathJax on Github!

**Comment by stla** [comment]
Yes, this works! Thanks again.

**Comment by stla** [comment]
Hello @fremling ,

I've done a R package with my C++ code and I included your name in the list of authors. My package can also evaluate the p-Weierstrass function.

I have a question about the generalized theta function in your code. I don't find it with Google. Would you have a reference please, or a link?

**Comment by fremling** [comment]
Thanks @stla, I'm honored.
As for a reference tot he generalized theta functions, I am also not sure where I stumbled across them the first time, they were kind of floating around as a natural parametrization in discussions. 

The basic properties are however given here M. Fremling, T. H. Hansson, and J. Suorsa, Phys. Rev. B 89, 125303 (2014), (Appendix F), (https://arxiv.org/pdf/1312.6038)
That paper is also the reason this fortran code was written in the first place.

**Comment by stla** [comment]
Thanks. Looks like it is in the appendix of [this thesis](https://core.ac.uk/download/pdf/48625256.pdf).

**Comment by stla** [comment]
My package is here, in case you want to mention it in your resume for example: <https://cran.r-project.org/web/packages/jacobi/index.html>.

And the Github repo, with beautiful pictures: <https://github.com/stla/jacobi>.
