### ISSUE TITLE
Reached 1000 iterations

### ISSUE THREAD

**Issue by stla** [fremling/jacobi-theta-function-fortran#3]
Hello,

 I found a value for which the 1000 iterations are attained when calculating `theta2`: $$z=0 \quad \text{and} \quad \tau = 0.7792256 +10^{-7}i.$$

This is really a edge case: with `tau = 0.78 + 1e-7`, this works.

There's a formula linking `theta(z, tau)` and `theta(z/tau, -1/tau)`, and one can get the result with this formula. One can see the presence of the edge case once again, because the imaginary part of `-1/tau` is `1.646924e-07`.

**Comment by stla** [comment]
The formula I'm talking about is the one you use when `(ABS(tau2).lt.0.98d0).AND.(AIMAG(tau2).lt.0.98d0)`. We gain something when `ABS(tau2) < 1`, theoretically speaking. I will try to play with this condition.

**Comment by stla** [comment]
Works with 4000 iterations.

**Comment by fremling** [comment]
I'm not surprised that you would run into problems, when $\tau$ is very close to the real line.
If you think about the modular space you are sitting deep inside the self similar regime, as the image below depicts.

I do not think that there is a nice way to solve this. The best I can suggest is to here try and work out the optimal way to perform S and T transformations, and apply these analytically first.....

![Modular_Space_ring](https://user-images.githubusercontent.com/13849332/176442970-d711502d-2ff9-49f4-8379-fb2d7b90c843.png)

**Comment by fremling** [comment]
I'm not sure what problem you are fundamentally trying to attack. However usually with these theta-functions, there is a primary domain given by $|\tau| \leq 1, |Re(\tau)| \leq 1/2$ where one tries to perform all calculations.

**Comment by stla** [comment]
Thanks. What is this picture exactly? I like it.

No problem, there are two possible fix: maxiter=4000 or tau -> -1/tau.

**Comment by stla** [comment]
Hey, how do you do inline Mathjax? That does not work for me: $\alpha$ and $\alpha$.

Source: `$\alpha$ and $\alpha$`.

**Comment by fremling** [comment]
> Thanks. What is this picture exactly? I like it.

It is a map of equivalent domains in the upper half of the $\tau$ plane.  All black (white) regions can be reached from the fundamental domain with an odd (even) number of modular transformations

$$ 
T: \tau  \to \tau + 1
\quad\quad \quad 
S: \tau  \to -1/\tau 
$$


For instance the cetern black "triangle" is obtained from the fundamental domain precisely by the transformation 
 $ \tau  \to -1/\tau $


(It's also the cover of my thesis.... )


<img src="https://user-images.githubusercontent.com/13849332/176453293-73f63d77-38af-488e-b6a1-98a6c05d0788.png" width="150">


> No problem, there are two possible fix: maxiter=4000 or tau -> -1/tau.

I recommend the latter... I would not trust the result anyway if I first needed to do 4000 modular transformations....

**Comment by fremling** [comment]
> Hey, how do you do inline Mathjax? That does not work for me:α\alpha$.
> 
> Source: `$\alpha$ and $\alpha$`.

I also have problems with this.... Not sure how to format multiple inline expressions simultaneously.

**Comment by stla** [comment]
Thanks. I've just compared the two methods. They give different results. Oddly, that's the maxiter=4000 method which gives the good result (taking Wolfram as reference). And the Python mpmath library gives a wrong result, strange.

**Comment by stla** [comment]
Ah no, Python is correct. I did a mistake (given tau in place of q).

**Comment by stla** [comment]
Ppfff... hard today :-(. *Both* methods work. Sorry for the confusion.

**Comment by fremling** [comment]
I could potentially include an optional argument allowing to set the
maxiter...

**Comment by stla** [comment]
Here is my strategy: maxiter=4000, throw a warning if iter reaches 1000, do a function which uses the -1/tau formula if ABS(tau) < 0.98, and recommend to the user to use this function if he/she gets the warning.

**Comment by fremling** [comment]
I had a look at it again. The problem was not even with the tau transformations. The problem was with the resulting shifts in z, which where done one tau-step at a time. In the example you gave z ~ 1300 tau which is why the max iteration was exceeded. The whole calculation is now done in one step and should work. If correct, the result for `z=(-0.0d0,0.0d0)`, `tau=(0.7792256d0,1.0d-7)`, is now

    res = (-46.426517230164478d0, -41.380842988230604d0)

The flag `maxiter` has also been added to allow the user to set the number of modular transformations higher if that should rally be necacarry.

**Comment by stla** [comment]
Hi @fremling 

I changed the method now. I no longer use your algorithm. Look at [this discussion](https://github.com/stla/EllipticFunctions.jl/pull/4) if you're interested.

**Comment by stla** [comment]
Argh! I've just tried this example and the code reaches 3000 iterations :-(

**Comment by fremling** [comment]
Modular transformations are tricky. Your suggestion was to use 1/tau once, but sometimes may transformations are necessary. The code i have makes several of these to move tau into the fundamental domain and then compute the theta function. 

The transformation rule for 1/tau is of course worked out by considering the Poisson ressumation that is mentioned in the discussion you link to.
